# Generated by Django 3.0.5 on 2020-06-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='webadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='webAdmin',
        ),
    ]
