# Generated by Django 3.0.5 on 2020-08-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0005_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Names',
        ),
    ]
