# Generated by Django 3.0.5 on 2020-08-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0008_webuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAdminLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('login_datetime', models.DateTimeField(auto_now=True)),
                ('login_username', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.CharField(default='0 minutes', max_length=50)),
                ('device_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'web_login_history',
                'verbose_name_plural': 'web login history',
            },
        ),
    ]
