# Generated by Django 3.0.5 on 2020-09-13 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0009_webadminloginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWGServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('pwg_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'PWG Servers',
            },
        ),
        migrations.AlterModelOptions(
            name='webadminloginhistory',
            options={'verbose_name': 'web_login_history', 'verbose_name_plural': 'webAdmin login history'},
        ),
        migrations.CreateModel(
            name='PWG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWGServers', verbose_name='PWGServers')),
            ],
            options={
                'verbose_name_plural': 'PWGs',
            },
        ),
    ]
