# Generated by Django 3.0.5 on 2020-09-14 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0010_auto_20200913_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webadminloginhistory',
            name='login_username',
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
