# Generated by Django 3.0.5 on 2020-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0011_auto_20200914_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webadminloginhistory',
            name='login_datetime',
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='login_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='login_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
