# Generated by Django 3.0.5 on 2020-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0014_auto_20200914_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webadminloginhistory',
            name='device_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
