# Generated by Django 3.0.5 on 2020-09-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0018_auto_20200915_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwg',
            name='transfer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pwgservers',
            name='transfer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwg',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWGServers', verbose_name='PWGServers'),
        ),
        migrations.AlterField(
            model_name='webadminloginhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
