# Generated by Django 3.0.5 on 2020-09-17 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0019_auto_20200916_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwg',
            old_name='transfer',
            new_name='transfer_to',
        ),
        migrations.RenameField(
            model_name='pwgservers',
            old_name='transfer',
            new_name='transfer_to',
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwg_name', models.CharField(max_length=255, null=True)),
                ('pwgs_name', models.CharField(max_length=255, null=True)),
                ('pwg_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWG')),
                ('pwgs_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWGServers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
