# Generated by Django 3.0.5 on 2020-09-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0020_auto_20200917_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPwg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwg_name', models.CharField(max_length=255, null=True)),
                ('pwg_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWG')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferPwgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwgs_name', models.CharField(max_length=255, null=True)),
                ('pwgs_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWGServers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
