# Generated by Django 3.0.5 on 2020-09-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0021_auto_20200918_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='alias',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='tester',
            name='last_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
