# Generated by Django 3.0.5 on 2020-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0023_auto_20200918_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tester',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
