# Generated by Django 3.0.5 on 2020-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0024_auto_20200919_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwg',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
    ]
