# Generated by Django 3.0.5 on 2020-09-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0025_pwg_is_tested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferpwg',
            options={'verbose_name': 'Transfer PWG', 'verbose_name_plural': 'Transfer PWGs'},
        ),
        migrations.AlterModelOptions(
            name='transferpwgs',
            options={'verbose_name': 'Transfer PWG Server', 'verbose_name_plural': 'Transfer PWG Servers'},
        ),
        migrations.RemoveField(
            model_name='transferpwg',
            name='pwg_name',
        ),
        migrations.RemoveField(
            model_name='transferpwgs',
            name='pwgs_name',
        ),
        migrations.AddField(
            model_name='transferpwg',
            name='pwgs_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWGServers'),
        ),
    ]
