# Generated by Django 3.0.5 on 2020-09-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0026_auto_20200920_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferpwg',
            name='pwg_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='transferpwgs',
            name='pwgs_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWGServers'),
        ),
    ]
