# Generated by Django 3.0.5 on 2020-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0027_auto_20200920_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwgservers',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pwgservers',
            name='password',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
