# Generated by Django 3.0.5 on 2020-09-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0028_auto_20200921_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwgservers',
            old_name='transfer_to',
            new_name='user',
        ),
    ]
