# Generated by Django 3.0.5 on 2020-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0031_auto_20200923_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwgUseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PWG Use Record',
                'verbose_name_plural': 'PWG Use Records',
            },
        ),
    ]
