# Generated by Django 3.0.5 on 2020-09-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0034_auto_20200927_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='alias',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
