# Generated by Django 3.0.5 on 2020-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0036_auto_20200928_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(default='none', upload_to='seller/'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='profile_pic',
            field=models.ImageField(default='none', upload_to='tester/'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='profile_pic',
            field=models.ImageField(default='none', upload_to='user/'),
        ),
    ]
