# Generated by Django 3.0.5 on 2020-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0037_auto_20200928_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnn', models.IntegerField()),
                ('yyyy', models.IntegerField()),
                ('mm', models.IntegerField()),
                ('dd', models.DateField()),
                ('hh', models.CharField(max_length=10)),
                ('serial_no', models.IntegerField()),
            ],
        ),
    ]
