# Generated by Django 3.0.5 on 2020-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0038_systemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemname',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='systemname',
            name='hh',
        ),
        migrations.RemoveField(
            model_name='systemname',
            name='mm',
        ),
        migrations.RemoveField(
            model_name='systemname',
            name='nnn',
        ),
        migrations.RemoveField(
            model_name='systemname',
            name='yyyy',
        ),
        migrations.AddField(
            model_name='systemname',
            name='is_pwgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemname',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemname',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemname',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemname',
            name='system_name',
            field=models.CharField(default='not assigned', max_length=19),
        ),
    ]
