# Generated by Django 3.0.5 on 2020-10-02 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0046_auto_20200930_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwg',
            name='sold_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemname',
            name='system_name',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.CreateModel(
            name='PWGHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('authorize', models.ForeignKey(default=None, null=True, on_delete=models.SET('object Deleted'), related_name='authorize_to', to=settings.AUTH_USER_MODEL)),
                ('get_on', models.ForeignKey(default=None, null=True, on_delete=models.SET('object Deleted'), related_name='admin_sold', to=settings.AUTH_USER_MODEL)),
                ('pwg', models.ForeignKey(default=None, null=True, on_delete=models.SET('object Deleted'), related_name='pwg', to='tesafe.PWG')),
                ('share', models.ForeignKey(default=None, null=True, on_delete=models.SET('object Deleted'), related_name='share_to', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(default=None, null=True, on_delete=models.SET('object Deleted'), related_name='transfer_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PWG History',
                'verbose_name_plural': 'PWG Histories',
            },
        ),
    ]
