# Generated by Django 3.0.5 on 2020-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0047_auto_20201002_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwghistory',
            old_name='authorize',
            new_name='object',
        ),
        migrations.RemoveField(
            model_name='pwghistory',
            name='get_on',
        ),
        migrations.RemoveField(
            model_name='pwghistory',
            name='share',
        ),
        migrations.RemoveField(
            model_name='pwghistory',
            name='transfer',
        ),
        migrations.AddField(
            model_name='pwghistory',
            name='action',
            field=models.TextField(default='None'),
        ),
    ]
