# Generated by Django 3.0.5 on 2020-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0048_auto_20201002_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwghistory',
            name='action',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
