# Generated by Django 3.0.5 on 2020-10-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0049_auto_20201002_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwg',
            old_name='sold_to',
            new_name='sold_from',
        ),
    ]
