# Generated by Django 3.0.5 on 2020-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0050_auto_20201003_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwghistory',
            name='action',
            field=models.CharField(default='N', max_length=3),
        ),
    ]
