# Generated by Django 3.0.5 on 2020-10-05 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0051_auto_20201003_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwg',
            name='sold_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold', to=settings.AUTH_USER_MODEL),
        ),
    ]
