# Generated by Django 3.0.5 on 2020-10-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0055_auto_20201007_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesterPWGHistory',
        ),
    ]
