# Generated by Django 3.0.5 on 2020-10-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0056_delete_testerpwghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterPWGHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('got_on', models.DateTimeField()),
                ('pwg_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesafe.PWG')),
            ],
            options={
                'verbose_name': 'Tester PWG Testing History',
                'verbose_name_plural': 'Tester PWG Testing Histories',
            },
        ),
    ]
