# Generated by Django 3.0.5 on 2020-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0057_testerpwghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='alias',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
