# Generated by Django 3.0.5 on 2020-10-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0058_auto_20201009_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerpwghistory',
            name='got_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
