# Generated by Django 3.0.5 on 2020-10-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0061_pwguserecord_pwg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('associated_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_user', to='tesafe.WebUser')),
                ('main_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user', to='tesafe.WebUser')),
            ],
            options={
                'verbose_name': 'User to User Association',
                'verbose_name_plural': 'User to User Associations',
            },
        ),
    ]
