# Generated by Django 3.0.5 on 2020-10-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0062_usertouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwguserecord',
            name='count',
        ),
    ]
