# Generated by Django 3.0.5 on 2020-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0063_remove_pwguserecord_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemname',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
