# Generated by Django 3.0.5 on 2020-10-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0065_auto_20201020_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='webadmin',
            name='system_name',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
    ]
