# Generated by Django 3.0.5 on 2020-10-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0067_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='first_name',
            field=models.CharField(default='No Name', max_length=100, null=True),
        ),
    ]
