# Generated by Django 3.0.5 on 2020-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0070_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
