# Generated by Django 3.0.5 on 2020-11-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0073_auto_20201111_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',)},
        ),
    ]
