# Generated by Django 3.0.5 on 2020-11-13 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0074_auto_20201112_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testerpwghistory',
            options={'verbose_name': 'Tester PWG History', 'verbose_name_plural': 'Tester PWG Histories'},
        ),
        migrations.CreateModel(
            name='TestedPWGHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('tested_on', models.DateTimeField(auto_now=True, null=True)),
                ('pwg_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwg_name', to='tesafe.PWG')),
                ('tester', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pwg_tester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tested PWG History',
                'verbose_name_plural': 'Tested PWG Histories',
            },
        ),
    ]
