# Generated by Django 3.0.5 on 2020-11-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0075_auto_20201113_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testedpwghistory',
            name='tested_on',
        ),
    ]
