# Generated by Django 3.0.5 on 2020-11-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0077_pwguserecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWGAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('a', models.BooleanField(default=False)),
                ('t', models.BooleanField(default=False)),
                ('s', models.BooleanField(default=False)),
                ('ds', models.BooleanField(default=False)),
                ('da', models.BooleanField(default=False)),
                ('pwg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tesafe.PWG')),
            ],
        ),
    ]
