# Generated by Django 3.0.5 on 2020-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0078_pwgattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwg',
            name='a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pwg',
            name='da',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pwg',
            name='ds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pwg',
            name='s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pwg',
            name='t',
            field=models.BooleanField(default=False),
        ),
    ]
