# Generated by Django 3.0.5 on 2020-11-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0079_auto_20201115_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwg',
            name='a',
        ),
        migrations.RemoveField(
            model_name='pwg',
            name='s',
        ),
        migrations.DeleteModel(
            name='PWGAttribute',
        ),
    ]
