# Generated by Django 3.0.5 on 2020-11-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0080_auto_20201115_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='seller/'),
        ),
        migrations.AlterField(
            model_name='tester',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tester',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tester',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='tester/'),
        ),
        migrations.AlterField(
            model_name='webadmin',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webadmin',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='user/'),
        ),
    ]
