# Generated by Django 3.0.5 on 2020-12-31 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0081_auto_20201130_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='device_name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='device_name_es_cl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='device_name_zn_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='last_pass_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='last_pass_es_cl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='last_pass_zn_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_date_en_us',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_date_es_cl',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_date_zn_ch',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_time_en_us',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_time_es_cl',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_time_zn_ch',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='alias_en_us',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='seller',
            name='alias_es_cl',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='seller',
            name='alias_zn_ch',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name_en_us',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name_es_cl',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name_zn_ch',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name_en_us',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name_es_cl',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name_zn_ch',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='first_name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='first_name_es_cl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='first_name_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='last_name_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='last_name_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='last_name_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='alias_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='alias_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='alias_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='first_name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='first_name_es_cl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='first_name_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='last_name_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='last_name_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='last_name_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='device_name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='device_name_es_cl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='device_name_zn_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='alias_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='alias_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='alias_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='first_name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='first_name_es_cl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='first_name_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='last_name_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='last_name_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='last_name_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='pwg',
            name='transfer_to',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwghistory',
            name='object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authorize_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwghistory',
            name='pwg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pwg', to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='pwgservers',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwguserecord',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='alias',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='testedpwghistory',
            name='pwg_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pwg_name', to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='testerpwghistory',
            name='pwg_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='usertouser',
            name='associated_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='associated_user', to='tesafe.WebUser'),
        ),
        migrations.AlterField(
            model_name='usertouser',
            name='main_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_user', to='tesafe.WebUser'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='associated_with',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tesafe.Seller'),
        ),
    ]
