# Generated by Django 3.0.5 on 2020-12-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0081_auto_20201130_1533'),
    ]

    operations = [

    ]
