# Generated by Django 3.0.5 on 2020-12-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0081_auto_20201130_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='device_name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='device_name_es_cl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='device_name_zn_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='last_pass_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='last_pass_es_cl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='last_pass_zn_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_date_en_us',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_date_es_cl',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_date_zn_ch',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_time_en_us',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_time_es_cl',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='login_time_zn_ch',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='alias_en_us',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='seller',
            name='alias_es_cl',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='seller',
            name='alias_zn_ch',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name_en_us',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name_es_cl',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name_zn_ch',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name_en_us',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name_es_cl',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name_zn_ch',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='alias_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='first_name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='first_name_es_cl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='first_name_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='last_name_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='last_name_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='last_name_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='alias_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='alias_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='alias_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='first_name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='first_name_es_cl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='first_name_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='last_name_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='last_name_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='last_name_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadmin',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='device_name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='device_name_es_cl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webadminloginhistory',
            name='device_name_zn_ch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='alias_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='alias_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='alias_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email_es_cl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email_zn_ch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='first_name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='first_name_es_cl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='first_name_zn_ch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='last_name_en_us',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='last_name_es_cl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='last_name_zn_ch',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='phone_en_us',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='phone_es_cl',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='phone_zn_ch',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='system_name_en_us',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='system_name_es_cl',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='webuser',
            name='system_name_zn_ch',
            field=models.CharField(default='not assigned', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='alias',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
    ]
