# Generated by Django 3.0.5 on 2021-01-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0082_auto_20201224_1630'),
        ('tesafe', '0082_auto_20201231_1352'),
    ]

    operations = [
    ]
