# Generated by Django 3.0.5 on 2021-01-09 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0083_merge_20210109_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
