# Generated by Django 3.0.5 on 2021-01-09 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tesafe', '0084_auto_20210109_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pwg',
            name='transfer_to',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwghistory',
            name='object',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authorize_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwghistory',
            name='pwg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pwg', to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='pwgservers',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pwguserecord',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='alias',
            field=models.CharField(default=None, help_text='Alias Name of the Seller', max_length=100, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(help_text='First Name of the Seller', max_length=100, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default=None, help_text='Last Name of the Seller', max_length=100, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='testedpwghistory',
            name='pwg_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pwg_name', to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='testerpwghistory',
            name='pwg_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tesafe.PWG'),
        ),
        migrations.AlterField(
            model_name='usertouser',
            name='associated_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='associated_user', to='tesafe.WebUser'),
        ),
        migrations.AlterField(
            model_name='usertouser',
            name='main_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_user', to='tesafe.WebUser'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='associated_with',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tesafe.Seller'),
        ),
    ]
