# Generated by Django 3.0.5 on 2021-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesafe', '0085_auto_20210109_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='give_notification',
            field=models.BooleanField(default=False, null=True),
        )
    ]
